version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: Django
    versions:
    - "= 3.x"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 99
