version: 2
jobs:

  build:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-metadeploy-py-{{ checksum "requirements.txt" }}
            - v1-metadeploy-py-
      - restore_cache:
          keys:
            - v1-metadeploy-npm-{{ checksum "yarn.lock" }}
            - v1-metadeploy-npm-
      - run:
          name: Install Node & Yarn
          command: ./bin/unpack-node
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
      - run:
          name: Update yarn.lock [greenkeeper]
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              yarn global add greenkeeper-lockfile@1 --prefix ~/metadeploy/node
              greenkeeper-lockfile-update
            fi
      - run:
          name: Install Dependencies
          command: |
            yarn
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Upload yarn.lock [greenkeeper]
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              greenkeeper-lockfile-upload
            fi
      - run:
          name: Check that yarn.lock matches package.json
          command: |
            if [[ ! "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              [[ $(git diff --name-only yarn.lock) == "" ]] && exit 0
              echo ">> yarn.lock is out of date, run \"yarn\""
              exit 1
            fi
      - run:
          name: Compile Front-End Assets
          command: yarn prod
      - save_cache:
          key: v1-metadeploy-node-{{ checksum "bin/unpack-node" }}
          paths:
            - "~/metadeploy/node"
      - save_cache:
          key: v1-metadeploy-py-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - ./venv
      - save_cache:
          key: v1-metadeploy-npm-{{ checksum "yarn.lock" }}
          paths:
            - "~/.cache/yarn"
            - "~/metadeploy/node_modules"
      - save_cache:
          key: v1-metadeploy-built-{{ .Revision }}
          paths:
            - "~/metadeploy/dist/prod"

  lint:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - restore_cache:
          key: v1-metadeploy-node-{{ checksum "bin/unpack-node" }}
      - restore_cache:
          key: v1-metadeploy-py-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: v1-metadeploy-npm-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-metadeploy-built-{{ .Revision }}
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            yarn lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
