version: 2
jobs:

  build:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-metadeploy-py-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/test.txt" }}
            - v1-metadeploy-py-
      - restore_cache:
          keys:
            - v1-metadeploy-npm-{{ checksum "yarn.lock" }}
            - v1-metadeploy-npm-
      - run:
          name: Install Node & Yarn
          command: ./bin/unpack-node
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
      - run:
          name: Update yarn.lock [greenkeeper]
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              yarn global add greenkeeper-lockfile@1 --prefix ~/metadeploy/node
              greenkeeper-lockfile-update
            fi
      - run:
          name: Install Dependencies
          command: |
            yarn
            python3 -m venv venv
            . venv/bin/activate
            unset PYTHONPATH
            pip install -r requirements/test.txt
      - run:
          name: Upload yarn.lock [greenkeeper]
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              greenkeeper-lockfile-upload
            fi
      - run:
          name: Check that yarn.lock matches package.json
          command: |
            if [[ ! "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              [[ $(git diff --name-only yarn.lock) == "" ]] && exit 0
              echo ">> yarn.lock is out of date, run \"yarn\""
              exit 1
            fi
      - run:
          name: Compile Front-End Assets
          command: yarn prod
      - save_cache:
          key: v1-metadeploy-node-{{ checksum "bin/unpack-node" }}
          paths:
            - "~/metadeploy/node"
      - save_cache:
          key: v1-metadeploy-py-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "~/.cache/pip"
            - ./venv
      - save_cache:
          key: v1-metadeploy-npm-{{ checksum "yarn.lock" }}
          paths:
            - "~/.cache/yarn"
            - "~/metadeploy/node_modules"

  lint:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          key: v1-metadeploy-node-{{ checksum "bin/unpack-node" }}
      - restore_cache:
          key: v1-metadeploy-py-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/test.txt" }}
      - restore_cache:
          key: v1-metadeploy-npm-{{ checksum "yarn.lock" }}
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            yarn lint

  test-client:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          key: v1-metadeploy-node-{{ checksum "bin/unpack-node" }}
      - restore_cache:
          key: v1-metadeploy-npm-{{ checksum "yarn.lock" }}
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
      - run:
          name: Test JS
          command: yarn test:coverage
      - run:
          name: Check JS Test Coverage
          command: |
            yarn test:report-coverage
            yarn test:check-coverage
      - store_artifacts:
          path: coverage
          destination: js-reports
      - store_test_results:
          path: coverage

  test-python:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.6.6
        environment:
          BUCKETEER_AWS_ACCESS_KEY_ID: access-key
          BUCKETEER_AWS_SECRET_ACCESS_KEY: secret-key
          BUCKETEER_BUCKET_NAME: a-bucket
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test
    steps:
      - checkout
      - restore_cache:
          key: v1-metadeploy-py-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/test.txt" }}
      - run:
          name: Run Database Migrations
          command: |
            . venv/bin/activate
            python ./manage.py migrate --no-input
      - run:
          name: Test Python
          command: |
            . venv/bin/activate
            pytest --junitxml=pycov/pytest-junit.xml
      - store_artifacts:
          path: htmlcov
          destination: py-reports
      - store_test_results:
          path: pycov

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-client:
          requires:
            - build
      - test-python:
          requires:
            - build
