# http://eslint.org/docs/rules/

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
env:
  browser: true
  node: false
plugins:
  - simple-import-sort
  - '@typescript-eslint'
extends:
  - plugin:@typescript-eslint/recommended
rules:
  # TypeScript
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/no-empty-function': 0
  '@typescript-eslint/no-explicit-any': 0

  # Import
  simple-import-sort/imports: 1
  import/order: 0
  import/no-duplicates: 0
