version: 1
update_configs:
  - package_manager: 'python'
    directory: '/'
    update_schedule: 'weekly'
    ignored_updates:
      - match:
          # django-rq-scheduler not compatible yet
          dependency_name: 'Django'
          version_requirement: '3.x'

  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
